steps:
#Creating a new instance template
- name: gcr.io/cloud-builders/gcloud
  id: create-instance-template
  args:
      - beta
      - compute
      - instance-templates
      - create
      - mohak-akbar-cloudbuild-template
      - --subnet=projects/prod-akbar-travels/regions/asia-south1/subnetworks/prod-apps-asia-sth1-subnet
      - --no-address
      - --image-project=prod-akbar-travels
      - --maintenance-policy=MIGRATE
      - --service-account=prod-akbar-jenkins-sa@prod-akbar-travels.iam.gserviceaccount.com
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --region=asia-south1-c
      - --tags=mig-rolling-update
      - --image=akbar-poc-img-1
      - --boot-disk-size=32GB
      - --boot-disk-type=pd-ssd
      - --boot-disk-device-name=mohak-akbar-boot-disk
      - --project=prod-akbar-travels
#Creating a test VM
- name: gcr.io/cloud-builders/gcloud
  id: create-test-vm
  args:
      - compute
      - instances
      - create
      - mohak-akbar-cloudbuild-vm
      - --source-instance-template=mohak-akbar-cloudbuild-template
      - --zone=asia-south1-a
      - --project=prod-akbar-travels
#Make sure that our MIG is stable before update
- name: gcr.io/cloud-builders/gcloud
  id: wait-until-stable
  args:
      - compute
      - instance-groups
      - managed
      - wait-until
      - mohak-instance-group
      - --stable
      - --region=asia-south1
#Updating the MIG with new instance template
- name: gcr.io/cloud-builders/gcloud
  id: updating-mig
  args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - mohak-instance-group
      - --version=template=mohak-akbar-cloudbuild-template{build number}
      - --type=proactive
      - --project=prod-akbar-travels
      - --region=asia-south1
      - --project=prod-akbar-travels
   # Deletion of test VM
- name: gcr.io/cloud-builders/gcloud
  id: deleting-test-vm
  args:
      - compute
      - instances
      - delete
      - mohak-akbar-cloudbuild-vm
      - --zone=asia-south1-a
      - --project=prod-akbar-travels

     
