steps:
# Creating a golden image
- name: gcr.io/cloud-builders/gcloud
  id: create-golden-image
  args:
    - compute
    - images
    - create
    - mohak-akbar-windows-img
    - --source-disk=mohak-instance-group-19z8
    - --source-disk-zone=asia-south1-c
    - --project=searce-playground
    - --force
#Creating a new instance template
- name: gcr.io/cloud-builders/gcloud
  id: create-instance-template
  args:
      - beta
      - compute
      - instance-templates
      - create
      - mohak-akbar-cloudbuild-template
      - --subnet=projects/searce-playground/regions/asia-south1/subnetworks/mohak-mumbai-subnet
      - --no-address
      - --maintenance-policy=MIGRATE
      - --service-account=mohak-56@searce-playground.iam.gserviceaccount.com
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --region=asia-south1
      - --tags=mig-rolling-update
      - --image=mohak-akbar-windows-img
      - --boot-disk-size=32GB
      - --boot-disk-type=pd-ssd
      - --boot-disk-device-name=mohak-akbar-boot-disk
      - --project=searce-playground
#Creating a test VM
- name: gcr.io/cloud-builders/gcloud
  id: create-test-vm
  args:
      - compute
      - instances
      - create
      - mohak-akbar-poc-new
      - --source-instance-template=mohak-akbar-cloudbuild-template
      - --zone=asia-south1-a
      - --project=searce-playground
#Make sure that our MIG is stable before update
- name: gcr.io/cloud-builders/gcloud
  id: wait-until-stable
  args:
      - compute
      - instance-groups
      - managed
      - wait-until
      - mohak-instance-group
      - --stable
      - --region=asia-south1
#Updating the MIG with new instance template
- name: gcr.io/cloud-builders/gcloud
  id: updating-mig
  args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - mohak-instance-group
      - --version=template=mohak-akbar-cloudbuild-template{build number}
      - --type=proactive
      - --region=asia-south1
      - --project=searce-playground
   # Deletion of test VM
- name: gcr.io/cloud-builders/gcloud
  id: deleting-test-vm
  args:
      - compute
      - instances
      - delete
      - instance-name
      - --zone=asia-south1-a
      - --project=tripoto-infra-prod

     
