steps:
# Creating a golden image
- name: gcr.io/cloud-builders/gcloud
  id: create-golden-image
  args:
    - compute
    - images
    - create
    - mohak-akbar-cloudbuild-img
    - --source-disk=mohak-akbar-mig-j6hk
    - --source-disk-zone=asia-south1-c
    - --project=prod-akbar-travels
    - --force
