steps:
- name: gcr.io/cloud-builders/gcloud
  id: wait-until-stable
  args:
      - beta
      - compute
      - instance-groups
      - managed
      - wait-until
      - mohak-akbar-mig
      - --stable
      - --project=prod-akbar-travels
      - --region=asia-south1
